identite_admin:
    resource: "@IdentiteAdminBundle/Resources/config/routing.yml"
    prefix:   /

identite_fiche:
    resource: "@IdentiteFicheBundle/Resources/config/routing.yml"
    prefix:   /

identite_profil:
    resource: "@IdentiteProfilBundle/Resources/config/routing.yml"
    prefix:   /
login_check:
    pattern: /login_check
<<<<<<< HEAD

rechercheFiche:
    resource: "@IdentiteFicheBundle/Resources/config/routing.yml"
    prefix: /
=======
IdentiteProfilBundle_inscription:
    resource: "@IdentiteProfilBundle/Resources/config/routing/identifiantsweb.yml"
    prefix:    /inscription 
>>>>>>> 5bda3a40597660524095cae5639246424240f07d
