identite_admin:
    resource: "@IdentiteAdminBundle/Resources/config/routing.yml"
    prefix:   /

identite_fiche:
    resource: "@IdentiteFicheBundle/Resources/config/routing.yml"
    prefix:   /

identite_profil:
    resource: "@IdentiteProfilBundle/Resources/config/routing.yml"
    prefix:   /
login_check:
    pattern: /login_check

rechercheFiche:
    resource: "@IdentiteFicheBundle/Resources/config/routing.yml"
    prefix: /