security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext  
      Identite\ProfilBundle\Entity\IdentifiantsWeb: plaintext

    #role_hierarchy:
        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
          entity: { class: Identite\ProfilBundle\Entity\IdentifiantsWeb }

        #in_memory:
            #memory:
                #users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~
         
              
        inscription_firewall:
            pattern: ^/inscription/nouveau
            anonymous: ~
            
        secured_area:
            pattern: ^/
            form_login: ~
            logout:
               path: /logout
               target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription/nouveau, roles: IS_AUTHENTICATED_ANONYMOUSLY }