security:

    acl:
      connection: default
      
    encoders:
      Symfony\Component\Security\Core\User\User: sha512  
      Identite\ProfilBundle\Entity\IdentifiantsWeb: sha512

    #role_hierarchy:
        #ROLE_ADMIN:       ROLE_USER
        #ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
          entity: { class: Identite\ProfilBundle\Entity\IdentifiantsWeb }

        #in_memory:
            #memory:
                #users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern: ^/login$
            anonymous: ~
         
              
        inscription_firewall:
            pattern: ^/inscription
            anonymous: ~
            
        #secured_area:
            #pattern: ^/
            #form_login: ~
            #logout:
               #path: /deconnection
               #target: /


    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
