identite_profil_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IdentiteProfilBundle:Default:index }
    
identiteprofil_homepage:
    pattern:  /login
    defaults: { _controller: IdentiteProfilBundle:Default:login }
    
identiteprofil_check:
    pattern:  /login_check
