identite_profil_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IdentiteProfilBundle:Default:index }

identite_page_deux:
    pattern:  /hello
    defaults: { _controller: IdentiteProfilBundle:Page2:index }

identite_error:
    pattern:  /{error}
    defaults: { _controller: IdentiteProfilBundle:Error:index }