identitelogin_homepage:
    pattern:  /login
    defaults: { _controller: IdentiteloginBundle:Default:login }
    
identitelogin_check:
    pattern:  /login_check
    
identitelogin_admin:
    pattern:  /admin
    defaults: { _controller: IdentiteloginBundle:Default:admin }