Identite\FicheBundle\Entity\Debriefing:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    texte:
      type: string
      length: 1000
      nullable: false
    creeLe:
      type: datetime
      nullable: false
    modifieLe:
      type: datetime
      nullable: false
    actif:
      type: boolean
      nullable: false
  manyToOne:
    fiche:
      targetEntity: Fiche
      inversedBy: debriefing
      joinColumns:
        fiche_id:
          referencedColumnName: id
    personne:
      targetEntity: Identite\ProfilBundle\Entity\Personne
      inversedBy: debriefing
      joinColumns:
        personne_id:
          referencedColumnName: id
