identite_fiche_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: IdentiteFicheBundle:Default:index }

IdentiteFicheBundle_fiche:
        resource: "@IdentiteFicheBundle/Resources/config/routing/fiche.yml"
        prefix:   /fiche
        
rechercherFiche:
        pattern: /rechercheFiche
        defaults: { _controller: IdentiteFicheBundle:Fiche:Recherche }

recherche:
        pattern: /recherche
        defaults: { _controller: IdentiteFicheBundle:Fiche:RechercheAvancee }
                    
