parameters:
#    identite_fiche.example.class: Identite\FicheBundle\Example
      
services:
#    identite_fiche.example:
#        class: %identite_fiche.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
