Identite\ProfilBundle\Entity\Permission:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nomPermission:
      type: string
      length: 50
      nullable: false
    description:
      type: string
      length: 1000
      nullable: false
  oneToMany:
    Autorise:
      targetEntity: Permission
      mappedBy: DependDe
  manyToOne:
    DependDe:
      targetEntity: Permission
      inversedBy: Autorise
      joinColumns:
        permission_id:
          referencedColumnName: id
  manyToMany:
    personne:
      targetEntity: Personne
      inversedBy: permission
      joinTable:
        name: Personne2Permission
        joinColumns:
          permission_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          personne_id:
            referencedColumnName: id
            nullable: false
    role:
      targetEntity: Role
      mappedBy: permission
