Identite\ProfilBundle\Entity\Permission:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nomPermission:
      type: string
      length: 50
      nullable: false
    description:
      type: string
      length: 1000
      nullable: false
  oneToMany:
    permission:
      targetEntity: Identite\Permission
      mappedBy: dependDe
  manyToOne:
    dependDe:
      targetEntity: Identite\Permission
      inversedBy: permission
      joinColumns:
        permission_id:
          referencedColumnName: id
  manyToMany:
    role:
      targetEntity: Identite\Role
      inversedBy: permission
      joinTable:
        name: Role2Permission
        joinColumns:
          permission_id2:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          role_id:
            referencedColumnName: id
            nullable: false
    personne:
      targetEntity: Identite\Personne
      inversedBy: permission
      joinTable:
        name: Personne2Permission
        joinColumns:
          permission_id2:
            referencedColumnName: id
            nullable: false
            unique: true
        inverseJoinColumns:
          personne_id:
            referencedColumnName: id
            nullable: false
