Identite\ProfilBundle\Entity\Personne:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 50
      nullable: false
    prenom:
      type: string
      length: 50
      nullable: true
    statut:
      type: string
      length: 50
      nullable: true
    creeLe:
      type: datetime
      nullable: false
    valideLe:
      type: datetime
      nullable: true
    premisDeConduire:
      type: boolean
      nullable: true
  oneToOne:
    identifiantsWeb:
      targetEntity: IdentifiantsWeb
      mappedBy: personne
      cascade: ["persist"]
    fichesValides:
      targetEntity: Identite\FicheBundle\Entity\Fiche
      mappedBy: validePar
    debriefing:
      targetEntity: Identite\FicheBundle\Entity\Debriefing
      mappedBy: personne
  manyToMany:
    fichesEcrites:
      targetEntity: Identite\FicheBundle\Entity\Fiche
      inversedBy: auteurs
      joinTable:
        name: Fiche2Personne
        joinColumns:
          personne_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          fiche_id:
            referencedColumnName: id
            nullable: false
    permission:
      targetEntity: Permission
      mappedBy: personne
    role:
      targetEntity: Role
      mappedBy: personne
    ficheRessource:
      targetEntity: Identite\FicheBundle\Entity\Fiche
      mappedBy: animateursRessources
