Identite\ProfilBundle\Entity\Personne:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 50
      nullable: false
    prenom:
      type: string
      length: 50
      nullable: true
    statut:
      type: string
      length: 50
      nullable: true
    creeLe:
      type: datetime
      nullable: false
    valideLe:
      type: datetime
      nullable: true
    permisDeConduire:
      type: bigint
      nullable: true
  oneToOne:
    identifiantsWeb:
      targetEntity: Identite\IdentifiantsWeb
      mappedBy: personne
  manyToMany:
    role:
      targetEntity: Role
      mappedBy: personne
    permission:
      targetEntity: Identite\Permission
      mappedBy: personne
