Identite\ProfilBundle\Entity\Role:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nom:
      type: string
      length: 50
      nullable: false
  manyToMany:
    personne:
      targetEntity: Personne
      inversedBy: role
      joinTable:
        name: Personne2Role
        joinColumns:
          role_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          personne_id:
            referencedColumnName: id
            nullable: false
    permission:
      targetEntity: Permission
      mappedBy: role
